In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
df = pd.read_csv('HousingData.csv')
df.head(10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,NaN,36.2
5,0.02985,0.0,2.18,0.0,0.458,6.430,58.7,6.0622,3,222,18.7,394.12,5.21,28.7
6,0.08829,12.5,7.87,NaN,0.524,6.012,66.6,5.5605,5,311,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5,311,15.2,396.90,19.15,27.1
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5,311,15.2,386.63,29.93,16.5
9,0.17004,12.5,7.87,NaN,0.524,6.004,85.9,6.5921,5,311,15.2,386.71,17.10,18.9

In [ ]:
df.isnull().sum()

CRIM       20
ZN         20
INDUS      20
CHAS       20
NOX         0
RM          0
AGE        20
DIS         0
RAD         0
TAX         0
PTRATIO     0
B           0
LSTAT      20
MEDV        0
dtype: int64

In [ ]:
X = df.drop('MEDV', axis=1)   # features
y = df['MEDV']                # target

In [ ]:
X = X.fillna(X.mean())
y = y.fillna(y.mean())

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
model = Sequential()

# Hidden layers (deep network)
model.add(Dense(64, activation='relu', input_shape=(X_train.shape[1],), name='input'))
model.add(Dense(32, activation='relu',name='layer_1'))

# Output layer (linear activation for regression)
model.add(Dense(1,name='output'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.compile(optimizer='adam', loss='mse', metrics=['mae'])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input (Dense)                   │ (None, 64)             │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ layer_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output (Dense)                  │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,009 (11.75 KB)

 Trainable params: 3,009 (11.75 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
history = model.fit(X_train, y_train, epochs=100, batch_size=16, validation_split=0.2)

Epoch 1/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 583.0801 - mae: 22.1143 - val_loss: 488.7036 - val_mae: 20.4577
Epoch 2/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 506.2113 - mae: 20.3425 - val_loss: 405.6689 - val_mae: 18.4040
Epoch 3/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 398.2658 - mae: 17.6626 - val_loss: 289.3342 - val_mae: 15.1665
Epoch 4/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 258.4697 - mae: 13.7032 - val_loss: 157.5830 - val_mae: 10.6512
Epoch 5/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 128.3567 - mae: 8.9767 - val_loss: 69.6963 - val_mae: 6.1322
Epoch 6/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 66.4464 - mae: 6.3002 - val_loss: 41.5919 - val_mae: 4.4990
Epoch 7/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 45.1318 - mae: 5.1700 - val_loss: 32.3333 - val_mae: 3.9680
Epoch 8/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 33.0688 - mae: 4.3264 - val_loss: 29.9157 - val_mae: 3.8581
Epoch 9/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 27.8639 - mae: 3.8444 - val_loss: 29.0802 - val_mae: 3.7957
Epoch 10/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 25.1519 - mae: 3.6373 - val_loss: 28.4666 - val_mae: 3.7771
Epoch 11/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 23.1464 - mae: 3.4900 - val_loss: 28.1332 - val_mae: 3.7109
Epoch 12/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 21.9514 - mae: 3.3691 - val_loss: 27.4644 - val_mae: 3.6500
Epoch 13/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 21.3465 - mae: 3.3799 - val_loss: 26.1944 - val_mae: 3.5552
Epoch 14/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 20.2028 - mae: 3.2466 - val_loss: 26.3872 - val_mae: 3.5378
Epoch 15/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 19.4778 - mae: 3.1857 - val_loss: 26.0813 - val_mae: 3.5328
Epoch 16/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 19.2157 - mae: 3.1974 - val_loss: 24.9176 - val_mae: 3.4632
Epoch 17/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 18.0819 - mae: 3.0794 - val_loss: 24.8440 - val_mae: 3.4545
Epoch 18/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 17.4846 - mae: 3.0237 - val_loss: 24.3330 - val_mae: 3.4117
Epoch 19/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 17.1073 - mae: 2.9984 - val_loss: 23.9894 - val_mae: 3.3905
Epoch 20/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 16.6450 - mae: 2.9257 - val_loss: 23.8674 - val_mae: 3.3923
Epoch 21/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 16.1946 - mae: 2.8824 - val_loss: 22.9567 - val_mae: 3.3257
Epoch 22/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 15.8257 - mae: 2.8641 - val_loss: 22.9481 - val_mae: 3.3456
Epoch 23/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 15.5007 - mae: 2.8105 - val_loss: 21.8756 - val_mae: 3.2495
Epoch 24/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 15.1572 - mae: 2.7887 - val_loss: 21.4193 - val_mae: 3.2342
Epoch 25/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 14.8078 - mae: 2.7686 - val_loss: 21.1006 - val_mae: 3.2054
Epoch 26/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 14.4251 - mae: 2.7173 - val_loss: 21.6700 - val_mae: 3.2777
Epoch 27/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 14.2195 - mae: 2.6924 - val_loss: 21.0604 - val_mae: 3.2368
Epoch 28/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 13.9136 - mae: 2.6588 - val_loss: 20.5733 - val_mae: 3.1908
Epoch 29/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 13.6458 - mae: 2.6457 - val_loss: 20.1012 - val_mae: 3.1667
Epoch 30/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 13.4515 - mae: 2.6117 - val_loss: 19.9056 - val_mae: 3.1554
Epoch 31/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 13.2745 - mae: 2.6161 - val_loss: 19.7632 - val_mae: 3.1367
Epoch 32/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.9943 - mae: 2.5653 - val_loss: 19.5821 - val_mae: 3.1326
Epoch 33/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.7943 - mae: 2.5516 - val_loss: 19.3633 - val_mae: 3.0916
Epoch 34/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.6033 - mae: 2.5255 - val_loss: 19.1328 - val_mae: 3.0782
Epoch 35/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 12.4730 - mae: 2.5079 - val_loss: 19.0009 - val_mae: 3.0792
Epoch 36/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.4165 - mae: 2.5301 - val_loss: 18.8107 - val_mae: 3.0539
Epoch 37/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.1082 - mae: 2.4746 - val_loss: 18.3892 - val_mae: 3.0479
Epoch 38/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 11.9724 - mae: 2.4608 - val_loss: 18.3244 - val_mae: 3.0296
Epoch 39/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 11.8914 - mae: 2.4464 - val_loss: 18.1340 - val_mae: 3.0136
Epoch 40/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 11.7955 - mae: 2.4581 - val_loss: 18.4288 - val_mae: 3.0329
Epoch 41/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 11.7473 - mae: 2.4329 - val_loss: 17.9315 - val_mae: 2.9993
Epoch 42/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 11.3998 - mae: 2.3917 - val_loss: 17.7362 - val_mae: 2.9940
Epoch 43/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.4685 - mae: 2.4244 - val_loss: 17.1458 - val_mae: 2.9691
Epoch 44/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 11.3819 - mae: 2.4171 - val_loss: 18.9016 - val_mae: 3.0017
Epoch 45/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 11.2595 - mae: 2.4576 - val_loss: 18.4233 - val_mae: 2.9952
Epoch 46/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 11.3122 - mae: 2.4346 - val_loss: 17.2347 - val_mae: 2.9091
Epoch 47/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.8247 - mae: 2.3455 - val_loss: 17.3879 - val_mae: 2.9173
Epoch 48/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.7083 - mae: 2.3696 - val_loss: 17.7755 - val_mae: 2.9596
Epoch 49/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.5509 - mae: 2.3245 - val_loss: 17.1208 - val_mae: 2.8816
Epoch 50/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.5358 - mae: 2.3342 - val_loss: 17.2332 - val_mae: 2.9015
Epoch 51/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.2812 - mae: 2.3174 - val_loss: 16.9667 - val_mae: 2.9125
Epoch 52/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.3903 - mae: 2.2949 - val_loss: 17.2537 - val_mae: 2.9022
Epoch 53/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.1319 - mae: 2.2833 - val_loss: 16.4934 - val_mae: 2.8536
Epoch 54/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.1718 - mae: 2.3063 - val_loss: 16.7289 - val_mae: 2.8701
Epoch 55/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.0046 - mae: 2.2640 - val_loss: 16.6775 - val_mae: 2.8527
Epoch 56/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9.8960 - mae: 2.2451 - val_loss: 16.7042 - val_mae: 2.8854
Epoch 57/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 10.0486 - mae: 2.3205 - val_loss: 16.5709 - val_mae: 2.8545
Epoch 58/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9.7269 - mae: 2.2389 - val_loss: 16.3286 - val_mae: 2.8283
Epoch 59/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.4225 - mae: 2.2177 - val_loss: 16.0179 - val_mae: 2.8325
Epoch 60/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 10.0335 - mae: 2.3346 - val_loss: 16.1696 - val_mae: 2.8307
Epoch 61/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 9.5363 - mae: 2.2280 - val_loss: 16.0629 - val_mae: 2.8139
Epoch 62/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.3082 - mae: 2.1952 - val_loss: 16.0628 - val_mae: 2.8029
Epoch 63/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.1791 - mae: 2.1833 - val_loss: 15.8578 - val_mae: 2.7938
Epoch 64/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9.4098 - mae: 2.2211 - val_loss: 15.9529 - val_mae: 2.7849
Epoch 65/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 9.2453 - mae: 2.2087 - val_loss: 15.4556 - val_mae: 2.7596
Epoch 66/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.0902 - mae: 2.2064 - val_loss: 15.7271 - val_mae: 2.8101
Epoch 67/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.9552 - mae: 2.1825 - val_loss: 15.6117 - val_mae: 2.7916
Epoch 68/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8035 - mae: 2.1499 - val_loss: 15.6869 - val_mae: 2.7872
Epoch 69/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8867 - mae: 2.1469 - val_loss: 15.5043 - val_mae: 2.7909
Epoch 70/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.7909 - mae: 2.1778 - val_loss: 15.0587 - val_mae: 2.7397
Epoch 71/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6837 - mae: 2.1414 - val_loss: 15.7081 - val_mae: 2.8028
Epoch 72/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3832 - mae: 2.1160 - val_loss: 14.9393 - val_mae: 2.7748
Epoch 73/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.5730 - mae: 2.1330 - val_loss: 15.0470 - val_mae: 2.7668
Epoch 74/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4735 - mae: 2.1162 - val_loss: 14.8957 - val_mae: 2.7544
Epoch 75/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3258 - mae: 2.1010 - val_loss: 15.4499 - val_mae: 2.8027
Epoch 76/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3613 - mae: 2.1010 - val_loss: 15.3663 - val_mae: 2.8096
Epoch 77/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.2592 - mae: 2.1135 - val_loss: 14.8969 - val_mae: 2.7546
Epoch 78/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.5210 - mae: 2.1331 - val_loss: 14.9807 - val_mae: 2.8074
Epoch 79/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.2248 - mae: 2.0978 - val_loss: 15.0022 - val_mae: 2.7784
Epoch 80/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1405 - mae: 2.0710 - val_loss: 15.0710 - val_mae: 2.7857
Epoch 81/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9584 - mae: 2.0674 - val_loss: 14.6250 - val_mae: 2.7244
Epoch 82/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0028 - mae: 2.0748 - val_loss: 14.2333 - val_mae: 2.6910
Epoch 83/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8247 - mae: 2.0519 - val_loss: 15.1079 - val_mae: 2.7954
Epoch 84/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9235 - mae: 2.0383 - val_loss: 15.1319 - val_mae: 2.7940
Epoch 85/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9957 - mae: 2.1426 - val_loss: 14.4745 - val_mae: 2.7267
Epoch 86/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9553 - mae: 2.0644 - val_loss: 14.6297 - val_mae: 2.7505
Epoch 87/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.6982 - mae: 2.0378 - val_loss: 15.0912 - val_mae: 2.7855
Epoch 88/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.5728 - mae: 2.0192 - val_loss: 14.2813 - val_mae: 2.7070
Epoch 89/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.4882 - mae: 1.9999 - val_loss: 14.6105 - val_mae: 2.7470
Epoch 90/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.3982 - mae: 1.9967 - val_loss: 14.8748 - val_mae: 2.7752
Epoch 91/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.3107 - mae: 1.9888 - val_loss: 14.3037 - val_mae: 2.7046
Epoch 92/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.3635 - mae: 1.9903 - val_loss: 14.5369 - val_mae: 2.7458
Epoch 93/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.4365 - mae: 2.0100 - val_loss: 14.1389 - val_mae: 2.7002
Epoch 94/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.7257 - mae: 2.0230 - val_loss: 15.4339 - val_mae: 2.7711
Epoch 95/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.4684 - mae: 2.0085 - val_loss: 14.6322 - val_mae: 2.7412
Epoch 96/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.1223 - mae: 1.9506 - val_loss: 14.5150 - val_mae: 2.7313
Epoch 97/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.2346 - mae: 2.0182 - val_loss: 14.7816 - val_mae: 2.7617
Epoch 98/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.1363 - mae: 1.9682 - val_loss: 14.5639 - val_mae: 2.7377
Epoch 99/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.9541 - mae: 1.9625 - val_loss: 13.9183 - val_mae: 2.6738
Epoch 100/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6.9343 - mae: 1.9163 - val_loss: 15.2366 - val_mae: 2.8175

In [ ]:
loss, mae = model.evaluate(X_test, y_test)
print("Test MAE:", mae)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 13.6355 - mae: 2.4283
Test MAE: 2.428283452987671

In [ ]:
predictions = model.predict(X_test)
print(predictions[:5])

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[[29.06378 ]
 [36.78357 ]
 [16.234856]
 [27.186033]
 [14.54929 ]]